############################
## HUGO MODULES
############################

imports:
  - path: github.com/HugoBlox/kit/modules/blox

mounts:
  - source: layouts
    target: layouts
  - source: assets
    target: assets
